changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - "**/*.story.{js,ts,tsx}"
  - "**/*.stories.{js,ts,tsx}"
  - javascript/webapp/**/*

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  3d-force-graph-ar@*:
    peerDependencies:
      three: "*"
  3d-force-graph-vr@*:
    peerDependencies:
      three: "*"
  "@datashaper/app-framework@*":
    peerDependencies:
      "@thematic/core": "*"
      "@thematic/d3": "*"
      "@thematic/fluent": "*"
      "@thematic/react": "*"
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      "@types/react-dom": "*"
      react: "*"
      react-dom: "*"
  aframe-forcegraph-component@*:
    peerDependencies:
      three: "*"
  elkjs@*:
    peerDependencies:
      web-worker: "*"
  react-force-graph@*:
    peerDependencies:
      three: "*"
  styled-components@*:
    dependencies:
      react-is: ^16
  "@thematic/fluent@*":
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
