packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@thematic/fluent@*":
    peerDependencies:
      "@fluentui/font-icons-mdl2": ^8.1.0
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      "@types/react-dom": "*"
      react: "*"
      react-dom: "*"
  apollo-server-fastify@*:
    dependencies:
      fast-json-stringify: "*"
  pino@*:
    peerDependencies:
      pino-pretty: "*"
  styled-components@*:
    dependencies:
      react-is: ^16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
