version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    profiles:
      - all

  backend_api:
    build: ./python/backend
    environment:
      - ENABLE_CORS=http://localhost:3000
      - REDIS_URL=redis://redis:6379/0
      - STORAGE=/data
    ports:
      - 8081:8081
    depends_on:
      - redis
    profiles:
      - all
      - backend

  backend_worker:
    build: ./python/backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WORKER=true
      - N_PARALLEL_JOBS=2
    depends_on:
      - redis
      - backend_api
    profiles:
      - all
      - backend

  redis:
    image: redis:6-alpine
    profiles:
      - all
      - backend
